### ISSUE TITLE
Getting this error on server load

### ISSUE THREAD

**Issue by jagodragon** [ShepherdJerred/sthorses#10]
`[21:25:38 ERROR]: Error occurred while enabling stHorses v1.1.5 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/NBTBase
        at com.shepherdjerred.sthorses.Main.onEnable(Main.java:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:749) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.Bukkit.reload(Bukkit.java:540) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:635) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.NBTBase
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
        ... 17 more
[21:25:38 INFO]: Server permissions file permissions.yml is empty, ignoring it
`

**Comment by ShepherdJerred** [comment]
You'll need to use a version that supports 1.9, the only release for 1.9.* works with 1.9.4, it can be found here https://github.com/ShepherdJerred/stHorses/releases/tag/1.1.8

**Comment by jagodragon** [comment]
oh.... the spigot update says updated to 1.11 though?

**Comment by jagodragon** [comment]
ok.. i have insatlled the mod properly now.... :p 

i am getting this error when i go to place the horse. 

`[15:08:55 ERROR]: Could not pass event PlayerInteractEvent to stHorses v2.0.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.UnsupportedOperationException: Not supported.
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftAbstractHorse.setVariant(CraftAbstractHorse.java:26) ~[spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at com.shepherdjerred.sthorses.listeners.PlaceListener.onInteractEvent(PlaceListener.java:99) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        ... 17 more
`

i get a new horse and loose the saddle.

**Comment by ShepherdJerred** [comment]
Looks like Spigot moved away from the variant attribute, so each type of horse is its own class. I'll see what I can do about fixing this error, thank you for reporting it.

**Comment by ShepherdJerred** [comment]
Fixed
